# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
# See https://circleci.com/docs/2.0/config-intro/#section=configuration for spec
#
version: 2.1

# Commands

commands:

  pull_cache:
    description: Pulls Quay.io docker images usable for our cache
    steps:
      - run: docker pull python:3.7.4-slim
      - run: docker pull quay.io/vsoch/freegenes:devel

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker
  docker: circleci/docker@0.5.13

workflows:
  version: 2.0

  # This builds on all pull requests to test, and ignores master
  build_without_deploy:
    jobs:
      - docker/publish:
          deploy: false
          image: vsoch/freegenes
          tag: latest
          extra_build_args: --cache-from=python:3.7.4-slim,quay.io/vsoch/freegenes:devel
          filters:
            branches:
              ignore: 
                - master
          before_build:
            - pull_cache
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(docker run --entrypoint cat quay.io/vsoch/freegenes /code/VERSION)
                   echo "Version that would be used for Docker tag is v${DOCKER_TAG}"

  # workflow publishes to Docker Hub, with each job having different triggers
  build_with_deploy:
    jobs:

        # Deploy versioned and latest images on tags (releases) only.
      - docker/publish:
          image: vsoch/freegenes
          registry: quay.io
          tag: latest
          extra_build_args: --cache-from=python:3.7.4-slim,quay.io/vsoch/freegenes:devel
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          before_build:
            - pull_cache
          after_build:
            - run:
                name: Publish Docker Tag with Version
                command: |
                   DOCKER_TAG=$(docker run --entrypoint cat quay.io/vsoch/freegenes /code/VERSION)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
                   docker tag quay.io/vsoch/freegenes:latest quay.io/vsoch/freegenes:${DOCKER_TAG}
                   docker push quay.io/vsoch/freegenes

  # publish devel to Docker Hub on merge to master
  build_with_deploy_devel:
    jobs:

      # Deploy devel tag on merge to master
      - docker/publish:
          image: vsoch/freegenes
          registry: quay.io
          tag: devel
          extra_build_args: --cache-from=python:3.7.4-slim,quay.io/vsoch/freegenes:devel
          before_build:
            - pull_cache
          filters:
            branches:
              only: master
          after_build:
            - run:
                name: Publish Development Docker Tags
                command: |
                   docker push quay.io/vsoch/freegenes:devel
